name: tangent
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: pix <andre.lipke@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  async: any
  tuple: any
  yaml: any
  dartis: any
  nyxx:
    path: '../nyxx'
  msgpack2: any
  json_serializable: any
  vm_service_lib: any
  llama:
    path: ../llama

dev_dependencies:
  pedantic: any
  test: any
  source_gen: any
